a = "AgACAgIAAxkBAAIBm2dO0pJpuCFzo7a0Ml2HhI24BoaoAALM6jEbRt55SgnAsH_HpjDWAQADAgADeAADNgQ'"

b = "AgACAgIAAxkBAAIBi2dOzt3BWVWeBLmFuskdsG8ZyhBZAAKm6jEbRt55Sk24QjirWUlkAQADAgADeAADNgQ"

c = "AgACAgIAAxkBAAIBm2dO0pJpuCFzo7a0Ml2HhI24BoaoAALM6jEbRt55SgnAsH_HpjDWAQADAgADbQADNgQ"





print(a==b)
